let box = document.createElement('img');
let boxIn = document.createElement('img');
let floor = document.createElement('img');
let wall = document.createElement('img');
let hole = document.createElement('img');
let leftFig = document.createElement('img');
let rightFig = document.createElement('img');
let upFig = document.createElement('img');
let downFig = document.createElement('img');
box.src = 'image/Box.png';
boxIn.src = 'image/Box_Inhole.png';
floor.src = 'image/Floor.png'
wall.src = 'image/Wall.png';
hole.src = 'image/Hole.png';
leftFig.src = 'image/Left.png';
rightFig.src = 'image/Right.png';
upFig.src = 'image/Up.png';
downFig.src = 'image/Down.png';