let box = document.createElement('img');
let boxIn = document.createElement('img');
let floor = document.createElement('img');
let wall = document.createElement('img');
let hole = document.createElement('img');
let leftFig = document.createElement('img');
let rightFig = document.createElement('img');
let upFig = document.createElement('img');
let downFig = document.createElement('img');
box.src = 'image/box.png';
boxIn.src = 'image/box_inhole.png';
floor.src = 'image/floor.png'
wall.src = 'image/wall.png';
hole.src = 'image/hole.png';
leftFig.src = 'image/left.png';
rightFig.src = 'image/right.png';
upFig.src = 'image/up.png';
downFig.src = 'image/down.png';